[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
optimize = true
optimizer_runs = 200
solc = "0.8.23"

# oppenzeppelin
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

# scripting
[rpc_endpoints]
sepolia = "${RPC_URL}"
gnosis = "${GNOSIS_MAINNET_RPC_URL}"

[etherscan]
gnosis = { key = "${GNOSIS_MAINNET_ETHERSCAN_API_KEY}" }

[profile.dependencies]
"@openzepplin-contracts" = { git = "https://github.com/OpenZeppelin/openzeppelin-contracts.git", tag = "v5.0.1" }
"@openzepplin-contracts-upgradeable" = { git = "https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable.git", tag = "v5.0.1" }
"@account-abstraction" = { git = "https://github.com/eth-infinitism/account-abstraction.git", tag = "v0.6.0" }